# Generated by CypressEditor
# 2018/3/9, 10:34:16

# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
wipe;                                    # 清 除
model basic -ndm 3 -ndf 6;               # 3维 ,6个 自 由 度
node 1 0 0 0;                            # 定 义 1.2节 点 X.Y.Z坐 标 
node 2 0 0 1300; 
fix 1 1 1 1 1 1 1;                       
fix 2 0 0 0 0 0 1;    
geomTransf PDelta 1 1 0 0;            # bianjie tiaojian yueshudian   

# ---------- 定 义 截 面 材 料   ------------------------------------------------------------------------------

# ----------核 心 区 混 凝 土     材 料 号     抗 压 强 度       峰 值 应  变       极 限 强  度       极 限 应 变     lamda      Ft       Ets
#uniaxialMaterial Concrete02  1        -35.7       -0.002364         -7.1         -0.021      0.1     3.57     1100  

# ----------保 护 层 混 凝 土     材 料 号     抗 压 强 度        峰 值 应 变        极 限 强 度        极 限 应 变     lamda      Ft        Ets
#uniaxialMaterial Concrete02  2        -30.5         -0.002         -6.1          -0.004      0.1     3.05    1100
     
#  ---------钢 筋            材 料 号      屈 服 强 度         弹 模           刚 度 比          R0      CR1     CR2     a1      a2    a3      4
#uniaxialMaterial Steel02     3         370           200000           0.02          18       0.925   0.001     0.05     1    -0.04   1

# ---------- 定 义 截 面 材 料   ------------------------------------------------------------------------------

# ----------核 心 区 混 凝 土     材 料 号     抗 压 强 度       峰 值 应  变       极 限 强  度       极 限 应 变     lamda      Ft       Ets
uniaxialMaterial Concrete02  1        -45        -0.002         -25       -0.028      0.1     3.57     1100  

# ----------保 护 层 混 凝 土     材 料 号     抗 压 强 度        峰 值 应 变        极 限 强 度        极 限 应 变     lamda      Ft        Ets
uniaxialMaterial Concrete02  2        -30.5         -0.002          -15.3          -0.004      0.1     3.05    1100
     
#  ---------钢 筋            材 料 号      屈 服 强 度         弹 模           刚 度 比          R0      CR1     CR2     a1      a2    a3      4
uniaxialMaterial Steel02     3         370           200000          0.01           20      0.925   0.001     0.05    1    -0.04   1



uniaxialMaterial Elastic 101 838125000
uniaxialMaterial Elastic 102 838125000
uniaxialMaterial Elastic 103 204000000000000
section Fiber 1 {

    # ---------划 分 纤 维 单 元--------------------------------------------
   
    #----------核 心 区 混 凝 土 --------------------------------------------
    #---矩 形 单 元 划 分   单 元 截 面 号   Y 方 向 划 分 个 数    Z方 向 划 分 个 数        1点 Y方 向 坐 标      1点 Z方 向  坐 标     2点 Y方 向 坐 标    2点 Z方 向 坐 标  
    patch rect          1              10               10                 -130.            -130.            130.           130.
    
    # ---------保 护 层 混 凝 土--------------------------------------------
    #---矩 形 单 元 划 分   单 元 截 面 号   Y 方 向 划 分 个 数     Z 方 向 划 分 个 数      1点 Y方 向 坐 标      1点 Z方 向 坐 标      2点 Y方 向 坐 标    2点 Z方 向 坐 标  
    patch rect          2              12               2                  -150.             130.            150.           150.
    patch rect          2              12               2                  -150.            -150.            150.          -130.
    patch rect          2               2              10                  -150.            -130.           -130.           130.
    patch rect          2               2              10                   130.            -130.            150.           130.
   
    #----------钢 筋 - ---------------------------------------------------
    # ---直 排 单 元   划 分 单 元 截 面 号      钢 筋 根 数          钢 筋 面 积         起 点 Y 方 向 坐 标    起 点 Z 方 向 坐 标    终 点  Y 方 向 坐 标   终 点 Z 方 向 坐 标 
    layer straight      3               4                154.                -135.           130.             135.           130.
    layer straight      3               2                154.                -135.           43.3             135.           43.3
    layer straight      3               2                154.                -135.          -43.3             135.           -43.3
    layer straight      3               4                154.                -135.          -130.             135.           -130.
}  
section Aggregator 11 101 Vy 102 Vz 103 T -section 1 
# -------- 定 义 梁 柱 单 元        单 元 号    节 点 1   节 点 2     高 斯 点 个 数    截 面 号    变 换 号   
#element nonlinearBeamColumn    1        1        2         5          11        1;  

element dispBeamColumn    1        1        2         5          11        1;  


# -------- 定 义  梁 柱 单 元    单 元 号   节 点 1   节 点 2    变 换 号    "HingeRadau $secTagI $LpI $secTagJ $LpJ $secTagInterior"     
#element forceBeamColumn    1        1        2       1     "HingeRadau   1     240      1    240         1" ;

recorder Node      -file   Xdisp.txt     -time    -node 2    -dof 1 disp;       
recorder Node      -file   Ydisp.txt     -time    -node 2    -dof 2 disp;      
recorder Node      -file   Zdisp.txt     -time    -node 2    -dof 3 disp;  
recorder Node      -file   XYdisp.txt     -time    -node 2    -dof 1 2 disp;  
recorder Node      -file   Xreaction.txt    -time    -node 1    -dof 1 reaction;                     
recorder Node      -file   Yreaction.txt    -time    -node 1    -dof 2 reaction;        
             
# ----------重 力 分 析   -----------------------------------------------------------------------------
pattern Plain 1 Linear {
    load 2 0 0 -576000 0 0 0;    #576kn，
 }

constraints Plain;                  
numberer Plain;                 
system BandGeneral;             
test EnergyIncr 1.0e-6 200;               
algorithm Newton;
integrator LoadControl 0.1;
analysis Static; 
analyze 10; 
puts "Gravity is ok" ;       

#------------------------dizhouwangfu-------------------------------
loadConst  -time 0.0;

set dt 1.0

# JP update
# timeSeries Path $tag -fileTime $fileTime -filePath $filePath <-factor $cFactor> <-useLast>
# X与Y向位移的时间交错进行
timeSeries  Path 101 -fileTime time1.txt -filePath dis1.txt ; # X方向位移
timeSeries  Path 202 -fileTime time2.txt -filePath dis2.txt ; # Y方向位移

#加载命令
#分别将107、108行的位移加载到荷载施加点的两个方向（位移荷载）

pattern Plain 2 101 {
    sp 2 1 1;
}
pattern Plain 23 202 {
    sp 2 2 1;
}
# 
#source LibAnalysisStaticParameters.tcl
# 施加重力
constraints Penalty 1.0e10 1.0e10;
numberer RCM;
system BandGeneral;
test NormUnbalance 1.0e-8 20 2;
algorithm NewtonLineSearch 0.75;
integrator LoadControl 1;
analysis Static;
integrator DisplacementControl 2 1 0.01;   

# 调入动力荷载的加载参数（直接调用官网的地震分析例子即可，拟静力加载和地震加载对Opensees来说是一样的，都是按照时间-荷载来处理
# 所以直接调用地震分析的算法迭代即可）

source LibAnalysisDynamicParameters.tcl; # 动力分析参数，参考根目录
set Tol 1e-20
set TmaxAnalysis 29014;
set DtAnalysis 1.0
set Nsteps [expr int($TmaxAnalysis/$DtAnalysis)];
set ok [analyze $Nsteps $DtAnalysis];			# actually perform analysis; returns ok=0 if analysis was successful

if {$ok != 0} {      				
	set ok 0;
	set controlTime [getTime];
	while {$controlTime < $TmaxAnalysis && $ok == 0} {
		set controlTime [getTime]
		set ok [analyze 1 $DtAnalysis]
		if {$ok != 0} {
			puts "Trying Newton with Initial Tangent .."
			test NormDispIncr   $Tol 1000  0
			algorithm Newton -initial
			set ok [analyze 1 $DtAnalysis]
			test $testTypeDynamic $TolDynamic $maxNumIterDynamic  0
			algorithm $algorithmTypeDynamic
		}
		if {$ok != 0} {
			puts "Trying Broyden .."
			algorithm Broyden 8
			set ok [analyze 1 $DtAnalysis]
			algorithm $algorithmTypeDynamic
		}
		if {$ok != 0} {
			puts "Trying NewtonWithLineSearch .."
			algorithm NewtonLineSearch .8
			set ok [analyze 1 $DtAnalysis]
			algorithm $algorithmTypeDynamic
		}
	}
};      # end if ok !0

puts $ok
puts "cyclic is ok"
# JP update
